# Ejercicio 2
Para el ejercicio 2, se han seleccionado tres fuentes, cada una relacionada con la temática de los premios Nobel de Química:
- [Fuente 1](https://en.wikipedia.org/wiki/List_of_Nobel_laureates_in_Chemistry): Tabla con los ganadores de los premios Nobel en Química, clasificados por año, nombre y país de procedencia
- [Fuente 2](https://en.wikipedia.org/wiki/List_of_nominees_for_the_Nobel_Prize_in_Chemistry): Nominados al premio Nobel de Química desde 1901 a 1970. El Comité Noruego del Nobel revela la lista de nominados hasta 50 años después de la fecha de nominación. Por esta razón, hasta la fecha, se cuenta con la lista oficial de nominados hasta 1973. Sin embargo, en la fuente que se empleará, solo se tiene información hasta 1970.
- [Fuente 3](https://en.wikipedia.org/wiki/List_of_Nobel_laureates_by_university_affiliation): Tabla con todos los ganadores de los premios Nobel, clasificados acorde a su afiliación a determinado instituto o universidad. Se deberá limpiar la tabla para filtrar solo los ganadores correspondientes al premio Nobel de Química.

## a) Fuente 1

In [1404]:
import pandas as pd

LaureatesLink="https://en.wikipedia.org/wiki/List_of_Nobel_laureates_in_Chemistry"
Laureates=pd.read_html(LaureatesLink,header=0,flavor='bs4')
type(Laureates)

list

In [1405]:
len(Laureates)

8

In [1406]:
Laureates=pd.read_html(LaureatesLink,header=0,flavor='bs4')
Laureates_DF=Laureates[0]
Laureates_DF

,Year,Image,Laureate[A],Country[B],Rationale[C],Ref
0,1901,NaN,Jacobus Henricus van 't Hoff (1852–1911),Netherlands,"""[for his] discovery of the laws of chemical d...",[18]
1,1902,NaN,Hermann Emil Fischer (1852–1919),Germany,"""[for] his work on sugar and purine syntheses""",[19]
2,1903,NaN,Svante August Arrhenius (1859–1927),Sweden,"""[for] his electrolytic theory of dissociation""",[20]
3,1904,NaN,Sir William Ramsay (1852–1916),United Kingdom,"""[for his] discovery of the inert gaseous elem...",[21]
4,1905,NaN,Adolf von Baeyer (1835–1917),Germany,"""[for] the advancement of organic chemistry an...",[22]
...,...,...,...,...,...,...
197,2022,NaN,Morten Meldal (b. 1954),Denmark,"""for the development of click chemistry and bi...",[126]
198,2022,NaN,K. Barry Sharpless (b. 1941),United States,"""for the development of click chemistry and bi...",[126]
199,2023,NaN,Moungi G. Bawendi (b. 1961),United States,"""for the discovery and synthesis of quantum dots""",[127]
200,2023,NaN,Louis E. Brus (b. 1943),United States,"""for the discovery and synthesis of quantum dots""",[127]
201,2023,NaN,Alexey Ekimov (b. 1945),Russia,"""for the discovery and synthesis of quantum dots""",[127]

In [1407]:
Laureates=pd.read_html(LaureatesLink,header=0,flavor='bs4')
Laureates_DF=Laureates[0]

#Eliminando las columnas "Image" y "Ref"
Laureates_DF.drop(columns=["Image","Ref"], inplace=True)

# Renombrando las columnas
Laureates_DF.rename(columns={"Year":"Year_of_award","Laureate[A]":"Laureate","Country[B]":"Country","Rationale[C]":"Rationale"},inplace=True)

#Creando dos nuevas columnas (Birth_year y Death_year a partir de datos preexistentes de la columna Laureate)
Laureates_DF_2=Laureates_DF["Laureate"].str.replace(pat=r'([a-zA-Z]+)',repl='',regex=True)
Laureates_DF_2=Laureates_DF_2.str.split("–", expand=True) #crear una columna para cada año

Laureates_DF_2[0]=Laureates_DF_2[0].str.replace(pat=r'(\D)',repl='',regex=True) #Eliminar no dígitos
Laureates_DF_2[1]=Laureates_DF_2[1].str.replace(pat=r'(\D)',repl='',regex=True) #Eliminar no dígitos

Laureates_DF["Birth_year"]=Laureates_DF_2[0]
Laureates_DF["Death_year"]=Laureates_DF_2[1]

# Limpiando la columna "Laureate" para que solo se encuentren los nombres de los ganadores
Laureates_DF["Laureate"]=Laureates_DF["Laureate"].str.replace(pat=r'(\d+)',repl='',regex=True) #eliminar dígitos correspondientes a los años
Laureates_DF["Laureate"]= Laureates_DF["Laureate"].str.replace(pat=' (–)',repl='') #eliminar ' (-)' ó '(b. )' que quedan
Laureates_DF["Laureate"]= Laureates_DF["Laureate"].str.replace(pat='(–)',repl='') #eliminar ' (-)' ó '(b. )' que quedan
Laureates_DF["Laureate"]= Laureates_DF["Laureate"].str.replace(pat=' (b. )',repl='') #eliminar (-) ó (b. ) que quedan
Laureates_DF["Laureate"]= Laureates_DF["Laureate"].str.replace(pat='(b. )',repl='') #eliminar (-) ó (b. ) que quedan

Laureates_DF["Laureate"]= Laureates_DF["Laureate"].str.strip() #eliminar espacios al inicio y al final

#Resultados:
Laureates_DF

,Year_of_award,Laureate,Country,Rationale,Birth_year,Death_year
0,1901,Jacobus Henricus van 't Hoff,Netherlands,"""[for his] discovery of the laws of chemical d...",1852,1911
1,1902,Hermann Emil Fischer,Germany,"""[for] his work on sugar and purine syntheses""",1852,1919
2,1903,Svante August Arrhenius,Sweden,"""[for] his electrolytic theory of dissociation""",1859,1927
3,1904,Sir William Ramsay,United Kingdom,"""[for his] discovery of the inert gaseous elem...",1852,1916
4,1905,Adolf von Baeyer,Germany,"""[for] the advancement of organic chemistry an...",1835,1917
...,...,...,...,...,...,...
197,2022,Morten Meldal,Denmark,"""for the development of click chemistry and bi...",1954,None
198,2022,K. Barry Sharpless,United States,"""for the development of click chemistry and bi...",1941,None
199,2023,Moungi G. Bawendi,United States,"""for the discovery and synthesis of quantum dots""",1961,None
200,2023,Louis E. Brus,United States,"""for the discovery and synthesis of quantum dots""",1943,None
201,2023,Alexey Ekimov,Russia,"""for the discovery and synthesis of quantum dots""",1945,None

In [1408]:
#Reemplazando valores "None" en la segunda columna con "Alive"
Laureates_DF['Death_year']=Laureates_DF_2[1].replace({None:'Alive'})

In [1409]:
#Revisando la columna 'Country'
# Se debe limpiar, porque algunos ganadores presentan más de una nacionalidad
set(Laureates_DF['Country']) # cada país está separado por '\xa0' o doble espacio

# Solo se mantendrá el primer país, porque corresponde al país de nacimiento
a = Laureates_DF['Country'].str.split("\xa0",expand=True) #separar por '\xa0'
a = a[0].str.split("  ",expand=True) #separar por doble espacio
a = a[0].str.split("[",expand=True) #para eliminar las referencias que se encuentran como números entre corchetes
a = a[0].str.split("(",expand=True)
a[0] = a[0].str.strip() #eliminar espacios al inicio y al final

Laureates_DF['Country_of_birth']=a[0]

#resultado:
set(Laureates_DF['Country_of_birth'])

{'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Czechoslovakia',
 'Denmark',
 'Finland',
 'France',
 'Germany',
 'Hungary',
 'Israel',
 'Italy',
 'Japan',
 'Kingdom of Yugoslavia',
 'Mexico',
 'Netherlands',
 'Norway',
 'Not awarded',
 'Poland',
 'Russia',
 'Soviet Union',
 'Sweden',
 'Switzerland',
 'United Kingdom',
 'United States',
 'West Germany',
 'Yugoslavia'}

In [1410]:
#Dataframe resultante
Laureates_DF=Laureates_DF.drop(columns={'Country':'Country_of_birth'})
Laureates_DF

,Year_of_award,Laureate,Rationale,Birth_year,Death_year,Country_of_birth
0,1901,Jacobus Henricus van 't Hoff,"""[for his] discovery of the laws of chemical d...",1852,1911,Netherlands
1,1902,Hermann Emil Fischer,"""[for] his work on sugar and purine syntheses""",1852,1919,Germany
2,1903,Svante August Arrhenius,"""[for] his electrolytic theory of dissociation""",1859,1927,Sweden
3,1904,Sir William Ramsay,"""[for his] discovery of the inert gaseous elem...",1852,1916,United Kingdom
4,1905,Adolf von Baeyer,"""[for] the advancement of organic chemistry an...",1835,1917,Germany
...,...,...,...,...,...,...
197,2022,Morten Meldal,"""for the development of click chemistry and bi...",1954,Alive,Denmark
198,2022,K. Barry Sharpless,"""for the development of click chemistry and bi...",1941,Alive,United States
199,2023,Moungi G. Bawendi,"""for the discovery and synthesis of quantum dots""",1961,Alive,United States
200,2023,Louis E. Brus,"""for the discovery and synthesis of quantum dots""",1943,Alive,United States
201,2023,Alexey Ekimov,"""for the discovery and synthesis of quantum dots""",1945,Alive,Russia

## b) Fuente 2

In [1411]:
import pandas as pd

NomineesLink="https://en.wikipedia.org/wiki/List_of_nominees_for_the_Nobel_Prize_in_Chemistry"
Nominees=pd.read_html(NomineesLink,header=0,flavor='bs4')
type(Nominees)

list

In [1412]:
range(len(Nominees))

range(0, 15)

In [1413]:
#El primer elemento de la lista es un DF que contiene adjuntos verticalmente datos de los nominados de 1901 a 1909
Nominees[0]

,Picture,Name,Born,Died,Years Nominated,Notes
0,1901.0,1901,1901,1901,1901,1901
1,NaN,Jacobus Henricus van 't Hoff,"August 30, 1852 Rotterdam, Netherlands","March 1, 1911 Berlin, Germany",1901,Won the 1901 Nobel Prize in Chemistry.[4]
2,NaN,Emil Fischer,"October 9, 1852 Euskirchen, Germany","July 15, 1919 Berlin, Germany","1901, 1902, 1916, 1919","Won the 1902 Nobel Prize in Chemistry,[5] late..."
3,NaN,Svante Arrhenius,"February 19, 1859 Uppsala, Sweden","October 2, 1927 Stockholm, Sweden","1901, 1902, 1903",Won the 1903 Nobel Prize in Chemistry and nomi...
4,NaN,Henri Moissan,"September 28, 1852 Paris, France","February 20, 1907 Paris, France","1901, 1902, 1903, 1904, 1905, 1906",Won the 1906 Nobel Prize in Chemistry.[8]
5,NaN,Zdenko Hans Skraup,"March 3, 1850 Prague, Czech Republic","September 10, 1910 Vienna, Austria",1901,Nominated the only time by Eduard Lippmann (18...
6,NaN,Marcellin Berthelot,"October 25, 1827 Paris, France","March 18, 1907 Paris, France","1901, 1902, 1903, 1904, 1906, 1907",[10]
7,NaN,William Jackson Pope,"March 31, 1870 London, England","October 17, 1939 Cambridge, England","1901, 1907, 1927",[11]
8,1902.0,1902,1902,1902,1902,1902
9,NaN,William Ramsay,"October 2, 1852 Glasgow, Scotland","July 23, 1916 High Wycombe, England","1902, 1903, 1904",Won the 1904 Nobel Prize in Chemistry and nomi...
10,NaN,Adolf von Baeyer,"October 31, 1835 Berlin, Germany","August 20, 1917 Starnberg, Germany","1902, 1903, 1904, 1905",Won the 1905 Nobel Prize in Chemistry.[13]
11,NaN,Theodore William Richards,"January 31, 1868 Germantown, Philadelphia, Uni...","April 2, 1928 Cambridge,_Massachusetts, United...","1902, 1905, 1908, 1909, 1910, 1911, 1912, 1913...",Won the 1914 Nobel Prize in Chemistry in 1915....
12,NaN,Rudolf Knietsch,"December 13, 1854 Opole, Poland","May 28, 1906 Ludwigshafen, Germany",1902,Nominated the only time by P.Klason.[15]
13,NaN,Johannes Wislicenus,"June 24, 1835 Querfurt, Germany","December 5, 1902 Leipzig, Germany",1902,Nominated the only time by Zd.H.Skraup.[16] Di...
14,NaN,Oliver Wolcott Gibbs,"February 21, 1822 New York City, United States","December 9, 1908 Portsmouth, Rhode Island, Uni...",1902,Nominated the only time by Ch.Edw.Munroe.[17]
15,NaN,Edward Williams Morley,"January 29, 1838 Newark, New Jersey, United St...","February 24, 1923 West Hartford, Connecticut, ...","1902, 1908, 1910",[18]
16,NaN,Armand Gautier,"September 23, 1837 Narbonne, France","July 27, 1920 Cannes, France","1902, 1916",Nominated for Nobel Prize in Physiology or Med...
17,1903.0,1903,1903,1903,1903,1903
18,NaN,Harmon Northrop Morse,"October 15, 1848 Cambridge, Vermont, United St...","September 8, 1920 Chebeague Island, Maine, Uni...","1903, 1910",Nominated by Harry Clary Jones (1865–1916) fro...
19,1904.0,1904,1904,1904,1904,1904
20,NaN,Wilhelm Ostwald,"September 2, 1853 Riga, Latvia","April 4, 1932 Grimma, Germany","1904, 1905, 1906, 1907, 1908, 1909",Won the 1909 Nobel Prize in Chemistry.[22]
21,1905.0,1905,1905,1905,1905,1905
22,NaN,Eduard Buchner,"May 20, 1860 Munich, Germany","August 13, 1917 Focșani, Romania","1905, 1907",Won the 1907 Nobel Prize in Chemistry and nomi...
23,NaN,Dmitri Mendeleev,"February 8, 1834 Tobolsk, Russia","February 2, 1907 Saint Petersburg, Russia","1905, 1906, 1907",[24]
24,NaN,Giacomo Ciamician,"August 27, 1857 Trieste, Italy","January 2, 1922 Bologna, Italy","1905, 1907, 1908, 1911, 1912, 1914, 1916, 1919...",[25]
25,NaN,Henry Louis Le Chatelier,"October 8, 1850 Paris, France","September 17, 1936 Miribel-les-Échelles, France","1905, 1907, 1908, 1909, 1914, 1915, 1920, 1921...",Nominated for the Nobel Prize in Physics too.[26]
26,1906.0,1906,1906,1906,1906,1906
27,NaN,Walther Nernst,"June 25, 1864 Gmina Wąbrzeźno, Poland","November 18, 1941 Niwica, Poland","1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913...",Won the 1920 Nobel Prize in Chemistry in 1921 ...
28,NaN,Victor Grignard,"May 6, 1871 Cherbourg-en-Cotentin, France","December 13, 1935 Lyon, France","1906, 1909, 1910, 1912, 1928",Won the 1912 Nobel Prize in Chemistry.[28]
29,1907.0,1907,1907,1907,1907,1907
30,NaN,Paul Sabatier,"November 5, 1854 Carcassonne, France","August 14, 1914 Toulouse, France","1907, 1909, 1911, 1912, 1928, 1929",Won the 1912 Nobel Prize in Chemistry.[29]
31,NaN,Ernest Rutherford,"August 30, 1871 Brightwater, New Zealand","October 19, 1937 Cambridge, England","1907, 1908",Won the 1908 Nobel Prize in Chemistry and nomi...
32,NaN,Otto Wallach,"March 27, 1847 Königsberg, Prussia","February 26, 1931 Göttingen, Germany","1907, 1908, 1910",Won the 1910 Nobel Prize in Chemistry.[31]
33,NaN,Alfred Werner,"December 12, 1866 Mulhouse, France","November 15, 1919 Zürich, Switzerland","1907, 1908, 1911, 1912, 1913",Won the 1913 Nobel Prize in Chemistry.[32]
34,NaN,Fredrik Adolf Kjellin,"April 24, 1872 Södertälje, Sweden","December 30, 1910 Stockholm, Sweden",1907,Nominated the only time by Otto Pettersson.[33]
35,NaN,Stanislao Cannizzaro,"July 13, 1826 Palermo, Italy","May 10, 1910 Rome, Italy",1907,[34]
36,NaN,Sophus Mads Jørgensen,"July 4, 1837 Slagelse, Denmark","April 1, 1914 Copenhagen, Denmark",1907,[35]
37,NaN,William Crookes,"June 17, 1832 London, England","April 4, 1919 London, England","1907, 1908, 1909, 1910",Nominated for the Nobel Prize in Physics too.[36]
38,NaN,Heinrich Caro,"February 13, 1834 Poznań, Poland","September 11, 1910 Dresden, Germany","1907, 1910",Nominated jointly with Ad.Frank only.[37]
39,NaN,Adolph Frank,"January 20, 1834 Klötze, Germany","May 30, 1916 Berlin, Germany","1907, 1910, 1916",[38]
40,NaN,Samuel Eyde,"October 29, 1866 Arendal, Norway","June 21, 1940 Åsgårdstrand, Norway","1907, 1909, 1913",Nominated jointly with Kr.Birkeland only.[39]
41,NaN,Kristian Birkeland,"December 13, 1867 Oslo, Norway","June 15, 1917 Kanagawa, Japan","1907, 1909, 1912, 1913",Nominated for the Nobel Prize in Physics too.[40]
42,NaN,Theodor Curtius,"May 27, 1857 Duisburg, Germany","February 8, 1928 Heidelberg, Germany","1907, 1908, 1909, 1910, 1913, 1914, 1916, 1917...",[41]
43,NaN,Albin Haller,"March 7, 1849 Fellering, France","April 29, 1925 Paris, France","1907, 1912, 1916, 1919, 1920, 1921, 1922, 1923...",[42]
44,1908.0,1908,1908,1908,1908,1908
45,NaN,Richard Willstätter,"August 13, 1872 Karlsruhe, Germany","August 3, 1942 Muralto, Switzerland","1908, 1909, 1911, 1912, 1913, 1914, 1915",Won the 1915 Nobel Prize in Chemistry.[43]
46,NaN,Frederick Soddy,"September 2, 1877 Eastbourne, England","September 22, 1956 Brighton, England","1908, 1918, 1919, 1922",Won the 1921 Nobel Prize in Chemistry in 1922....
47,NaN,Albrecht Kossel,"September 16, 1853 Rostock, Germany","July 5, 1927 Heidelberg, Germany",1908,Won the 1910 Nobel Prize in Physiology or Medi...
48,NaN,Gustaf de Laval,"May 9, 1845 Orsa, Sweden","February 2, 1913 Stockholm, Sweden",1908,Nominated the only time by Otto Pettersson and...
49,NaN,Georg Lunge,"September 15, 1839 Wrocław, Poland","January 3, 1923 Zürich, Switzerland",1908,[47]
50,NaN,Arthur Rudolf Hantzsch,"March 7, 1857 Dresden, Germany","March 14, 1935 Dresden, Germany","1908, 1927",[48]
51,1909.0,1909,1909,1909,1909,1909
52,NaN,Edmund Oscar von Lippmann,"January 9, 1857 Vienna, Austria","September 24, 1940 Halle (Saale), Germany",1909,Nominated the only time by Alexander Herzfeld ...
53,NaN,Hans Heinrich Landolt,"December 5, 1831 Zürich, Switzerland","March 15, 1910 Berlin, Germany","1909, 1910",[50]
54,NaN,Otto Schönherr,"December 1, 1861 Chemnitz, Germany","December 25, 1926 Dresden, Germany","1909, 1912",[51]
55,NaN,Karl Engler,"January 5, 1842 Weisweil, Germany","February 7, 1925 Karlsruhe, Germany","1909, 1910, 1911, 1916",[52]
56,NaN,Jean-Baptiste Senderens,"January 27, 1856 Barbachen, France","September 26, 1937 Barbachen, France","1909, 1928, 1929",Nominated jointly with P.Sabatier only.[53]
57,NaN,Gabriel Bertrand,"May 17, 1867 Paris, France","June 10, 1962 Paris, France","1909, 1928, 1929, 1931, 1932, 1933, 1934, 1935...",Nominated for Nobel Prize in Physiology or Med...

### b.2) Filtrado y concatenación de la data

In [1414]:
# Con la función cotas, se busca encontrar el intervalo de filas donde se encuentran los nominados por cada año
# Con esto, acotar los DFs asociados a cada año, en función a dicho intervalo de filas
# x: índice de la lista Nominees, y: año de nominación
# Por ejemplo, los que fueron nominados en 1901, se encuentran en las filas 1:7 del elemento 1 de la lista Nominees

def cotas(x,y):
    try:
        cota_inf=Nominees[x].index.get_loc(Nominees[x][Nominees[x]['Picture'] == y].index[0])
        cota_sup= Nominees[x].index.get_loc(Nominees[x][Nominees[x]['Picture'] == y+1].index[0])
        return range(cota_inf+1,cota_sup)
    except:
        cota_inf=Nominees[x].index.get_loc(Nominees[x][Nominees[x]['Picture'] == y].index[0])
        cota_sup= Nominees[x].shape[0]
        return range(cota_inf+1,cota_sup)
    

list(cotas(0,1901))

[1, 2, 3, 4, 5, 6, 7]

Se tiene información de los nominados desde 1901 hasta 1970 en forma de 8 DFS:

- 1901–1909: Nominees[0]
- 1910–1919: Nominees[1]
- 1920–1929: Nominees[2]
- 1930–1939: Nominees[3]
- 1940–1949: Nominees[4]
- 1950–1959: Nominees[5]
- 1960–1969: Nominees[6]
- 1970: Nominees[7]

In [1415]:
#DFs de 1901-1909
NomineesDFs_1901_1909=[Nominees[0].iloc[cotas(0,i),:] for i in list(range(1901,1910))]

# DFs de 1910 a 1969
    #Forma larga:
NomineesDFs_1910_1919=[Nominees[1].iloc[cotas(1,i),:] for i in list(range(1910,1920))]
NomineesDFs_1920_1929=[Nominees[2].iloc[cotas(2,i),:] for i in list(range(1920,1930))]
NomineesDFs_1930_1939=[Nominees[3].iloc[cotas(3,i),:] for i in list(range(1930,1940))]
NomineesDFs_1940_1949=[Nominees[4].iloc[cotas(4,i),:] for i in list(range(1940,1950))]
NomineesDFs_1950_1959=[Nominees[5].iloc[cotas(5,i),:] for i in list(range(1950,1960))]
NomineesDFs_1960_1969=[Nominees[6].iloc[cotas(6,i),:] for i in list(range(1960,1970))]
    #Forma simplificada: 
NomineesDFs_1910_1969=[Nominees[j].iloc[cotas(j,i),:] for j in list(range(1,7)) for i in list(range(1900+j*10,1910+j*10))]


#DF de 1970 
#Los datos Nominees[7].Picture no se encontraban como números reales (float)
#Por esto, se tuvo que realizar la conversión respectiva
Nominees[7].Picture=pd.to_numeric(Nominees[7].Picture,errors='coerce')
NomineesDF_1970=Nominees[7].iloc[cotas(7,1970),:]

In [1416]:
#Concatenando los DFs de cada lista
Nominees=pd.read_html(NomineesLink,header=0,flavor='bs4')
NomineesDFs_1901_1909=[Nominees[0].iloc[cotas(0,i),:] for i in list(range(1901,1910))]
NomineesDFs_1901_1909=pd.concat(NomineesDFs_1901_1909[i] for i in range(len(NomineesDFs_1901_1909))) 

NomineesDFs_1910_1969=[Nominees[j].iloc[cotas(j,i),:] for j in list(range(1,7)) for i in list(range(1900+j*10,1910+j*10))]
NomineesDFs_1910_1969=pd.concat(NomineesDFs_1910_1969[i] for i in range(len(NomineesDFs_1910_1969))) 

Nominees[7].Picture=pd.to_numeric(Nominees[7].Picture,errors='coerce')
NomineesDF_1970=Nominees[7].iloc[cotas(7,1970),:]

NomineesList=[NomineesDFs_1901_1909,NomineesDFs_1910_1969,NomineesDF_1970]
NomineesAllDFs=pd.concat(NomineesList)
NomineesAllDFs

,Picture,Name,Born,Died,Years Nominated,Notes,Unnamed: 6
1,NaN,Jacobus Henricus van 't Hoff,"August 30, 1852 Rotterdam, Netherlands","March 1, 1911 Berlin, Germany",1901,Won the 1901 Nobel Prize in Chemistry.[4],NaN
2,NaN,Emil Fischer,"October 9, 1852 Euskirchen, Germany","July 15, 1919 Berlin, Germany","1901, 1902, 1916, 1919","Won the 1902 Nobel Prize in Chemistry,[5] late...",NaN
3,NaN,Svante Arrhenius,"February 19, 1859 Uppsala, Sweden","October 2, 1927 Stockholm, Sweden","1901, 1902, 1903",Won the 1903 Nobel Prize in Chemistry and nomi...,NaN
4,NaN,Henri Moissan,"September 28, 1852 Paris, France","February 20, 1907 Paris, France","1901, 1902, 1903, 1904, 1905, 1906",Won the 1906 Nobel Prize in Chemistry.[8],NaN
5,NaN,Zdenko Hans Skraup,"March 3, 1850 Prague, Czech Republic","September 10, 1910 Vienna, Austria",1901,Nominated the only time by Eduard Lippmann (18...,NaN
...,...,...,...,...,...,...,...
26,NaN,Charles Gilbert Overberger,"October 12, 1920 Barnesboro, Pennsylvania, Uni...","March 17, 1997 Ann Arbor, United States",1970,Jointly nominated with K.J.Freudenberg and Al....,NaN
27,NaN,Henry Montague (Monty) Frey,"February 27, 1929 London, England",NaN,1970,Jointly nominated the only time by Youssef Isk...,NaN
28,NaN,Jack Sylvester Hine,"July 2, 1923 Coronado, California, United States","July 6, 1988 Columbus, Ohio, United States",1970,Jointly nominated the only time by Youssef Isk...,NaN
29,NaN,Wolfgang Kirmse,"June 26, 1930 Frankfurt am Main, Germany",NaN,1970,Jointly nominated the only time by Youssef Isk...,NaN
30,NaN,Tetsuo Nozoe,"May 16, 1902 Sendai, Japan","April 4, 1996 Tokyo, Japan","1970, 1974[747]",[748],NaN

### b.2) Limpieza del DataFrame resultante de la concatenación

In [1417]:
NomineesAllDFs=pd.concat(NomineesList)

# Manteniendo solo el país en los valores de la columna Born
a=NomineesAllDFs['Born'].str.split(',',expand=True)
a[2]=a[2].str.replace(pat=r'\d|\s|\W',repl="",regex=True) #country
NomineesAllDFs["Country"]=a[2]

#Eliminando y renombrando columnas
NomineesAllDFs=NomineesAllDFs.drop(columns=['Picture','Notes','Unnamed: 6','Born','Died'])
NomineesAllDFs=NomineesAllDFs.rename(columns={'Name':'Nominee','Years Nominated':'Years_Nominated'})

NomineesAllDFs

,Nominee,Years_Nominated,Country
1,Jacobus Henricus van 't Hoff,1901,Netherlands
2,Emil Fischer,"1901, 1902, 1916, 1919",Germany
3,Svante Arrhenius,"1901, 1902, 1903",Sweden
4,Henri Moissan,"1901, 1902, 1903, 1904, 1905, 1906",France
5,Zdenko Hans Skraup,1901,CzechRepublic
...,...,...,...
26,Charles Gilbert Overberger,1970,Pennsylvania
27,Henry Montague (Monty) Frey,1970,England
28,Jack Sylvester Hine,1970,California
29,Wolfgang Kirmse,1970,Germany
30,Tetsuo Nozoe,"1970, 1974[747]",Japan

In [1418]:
#Limpieza de la columna años de nominación

#Eliminar espacios
NomineesAllDFs['Years_Nominated']=NomineesAllDFs['Years_Nominated'].str.replace(pat=r'\s',repl="",regex=True)

#Eliminar números separados por "[", porque aluden a referencias. Ejm: [747] se refiere a la referencia 747 de la fuente 2
NomineesAllDFs['Years_Nominated']=NomineesAllDFs['Years_Nominated'].str.split("[",expand=True)[0]

NomineesAllDFs

                         Nominee                Years_Nominated        Country
1   Jacobus Henricus van 't Hoff                           1901    Netherlands
2                   Emil Fischer            1901,1902,1916,1919        Germany
3               Svante Arrhenius                 1901,1902,1903         Sweden
4                  Henri Moissan  1901,1902,1903,1904,1905,1906         France
5             Zdenko Hans Skraup                           1901  CzechRepublic
..                           ...                            ...            ...
26    Charles Gilbert Overberger                           1970   Pennsylvania
27   Henry Montague (Monty) Frey                           1970        England
28           Jack Sylvester Hine                           1970     California
29               Wolfgang Kirmse                           1970        Germany
30                  Tetsuo Nozoe                      1970,1974          Japan

[640 rows x 3 columns]

In [1419]:
#Ordenando el DF por año (una fila para cada año de nominación)
NomineesAllDFs_Long=NomineesAllDFs.copy()
NomineesAllDFs_Long['Years_Nominated']=NomineesAllDFs_Long['Years_Nominated'].str.split(",")
NomineesAllDFs_Long=NomineesAllDFs_Long.explode('Years_Nominated')
NomineesAllDFs_Long.reset_index(drop=True,inplace=True)
NomineesAllDFs_Long

                           Nominee Years_Nominated      Country
0     Jacobus Henricus van 't Hoff            1901  Netherlands
1                     Emil Fischer            1901      Germany
2                     Emil Fischer            1902      Germany
3                     Emil Fischer            1916      Germany
4                     Emil Fischer            1919      Germany
...                            ...             ...          ...
2028   Henry Montague (Monty) Frey            1970      England
2029           Jack Sylvester Hine            1970   California
2030               Wolfgang Kirmse            1970      Germany
2031                  Tetsuo Nozoe            1970        Japan
2032                  Tetsuo Nozoe            1974        Japan

[2033 rows x 3 columns]

**Problema**: Los años 152, 153 y 1974* deben ser corregidos. 
*Nota: la lista oficial de candidatos al nobel aparece 50 años luego de la fecha de nominación, por lo que aún no se han pubiclado los nominados en 1974

In [1420]:
#Transformación de la tabla a horizontal
NomineesAllDFs_Wide=pd.pivot_table(NomineesAllDFs_Long,
               values=["Nominee"], # values to use
               index=['Country'], # unit of analysis
               columns=['Years_Nominated'], # the values for NEW column
                aggfunc=lambda x: ' '.join(str(v) for v in x))

NomineesAllDFs_Wide

                      Nominee                                               \
Years_Nominated           152  153 1901 1902 1903 1904 1905 1906 1907 1908
Country
Argentina                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Armenia                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Australia                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Austria                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Belarus                   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...                       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
WestRidingofYorkshire     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Wiltshire                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Wisconsin                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
nowPoland                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
nowUkraine                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

                       ...                                        \
Years_Nominated        ...                                  1962
Country                ...
Argentina              ...                                   NaN
Armenia                ...                                   NaN
Australia              ...                                   NaN
Austria                ...  Max Perutz Fritz Feigl Carl Djerassi
Belarus                ...                                   NaN
...                    ...                                   ...
WestRidingofYorkshire  ...                                   NaN
Wiltshire              ...                                   NaN
Wisconsin              ...                                   NaN
nowPoland              ...                                   NaN
nowUkraine             ...                                   NaN

                                                              \
Years_Nominated                          1963           1964
Country
Argentina                                 NaN            NaN
Armenia                                   NaN            NaN
Australia                                 NaN            NaN
Austria                Max Perutz Fritz Feigl  Carl Djerassi
Belarus                                   NaN            NaN
...                                       ...            ...
WestRidingofYorkshire                     NaN            NaN
Wiltshire                                 NaN            NaN
Wisconsin                                 NaN            NaN
nowPoland                        Fritz London            NaN
nowUkraine                                NaN            NaN

                                                                      \
Years_Nominated                                                 1965
Country
Argentina                                                        NaN
Armenia                                            Oganes K. Davtyan
Australia                                  John Warcup Cornforth Jr.
Austria                Herman Francis Mark Carl Djerassi Otto Kratky
Belarus                                                          NaN
...                                                              ...
WestRidingofYorkshire                                            NaN
Wiltshire                                                        NaN
Wisconsin                                      James Elliot Carnahan
nowPoland                                                        NaN
nowUkraine                                            Erwin Chargaff

                                                  \
Years_Nominated                             1966
Country
Argentina                                    NaN
Armenia                                      NaN
Australia              John Warcup Cornforth Jr.
Austria                Fritz Feigl Carl Djerassi
Belarus                                      NaN
...                                          ...
WestRidingofYorkshire                        NaN
Wiltshire                                    NaN
Wisconsin                                    NaN
nowPoland                                    NaN
nowUkraine                       Bernard Halpern

                                                                    \
Years_Nominated                                               1967
Country
Argentina                                                      NaN
Armenia                                                        NaN
Australia                                John Warcup Cornforth Jr.
Austria                Fritz Feigl Herman Francis Mark Otto Kratky
Belarus                                                        NaN
...                                                            ...
WestRidingofYorkshire                           Geoffrey Wilkinson
Wiltshire                                 Frederick Robert Whatley
Wisconsin                                                      NaN
nowPoland                                Max Rudolf "Rudi" Lemberg
nowUkraine                                          Erwin Chargaff

                                                                          \
Years_Nominated                                                     1968
Country
Argentina                                                            NaN
Armenia                                                              NaN
Australia                                      John Warcup Cornforth Jr.
Austria                Herman Francis Mark Carl Djerassi Otto Kratky ...
Belarus                                       Yakov Borisovich Zeldovich
...                                                                  ...
WestRidingofYorkshire                                 Geoffrey Wilkinson
Wiltshire                                                            NaN
Wisconsin                                                            NaN
nowPoland                                                            NaN
nowUkraine                                                           NaN

                                                                          \
Years_Nominated                                                     1969
Country
Argentina                                                            NaN
Armenia                                                              NaN
Australia                       John Warcup Cornforth Jr. Rowland Pettit
Austria                Herman Francis Mark Carl Djerassi Otto Kratky ...
Belarus                                                              NaN
...                                                                  ...
WestRidingofYorkshire                                 Geoffrey Wilkinson
Wiltshire                                                            NaN
Wisconsin                                                            NaN
nowPoland                      Konstantin Antonovich Petrzhak (Pietrzak)
nowUkraine                                             David Nachmansohn


Years_Nominated                                                   1970 1974
Country
Argentina                                                          NaN  NaN
Armenia                                                            NaN  NaN
Australia                                    John Warcup Cornforth Jr.  NaN
Austria                Herman Francis Mark Carl Djerassi Klaus Biemann  NaN
Belarus                                                            NaN  NaN
...                                                                ...  ...
WestRidingofYorkshire                               Geoffrey Wilkinson  NaN
Wiltshire                                                          NaN  NaN
Wisconsin                                                          NaN  NaN
nowPoland                                                          NaN  NaN
nowUkraine                                                         NaN  NaN

[99 rows x 73 columns]

In [1421]:
# Filas de nominados, donde hay error en los años
NomineesAllDFs_Long.loc[NomineesAllDFs_Long['Years_Nominated']=='152'] #Jaroslav Heyrovský
NomineesAllDFs_Long.loc[NomineesAllDFs_Long['Years_Nominated']=='153'] #Jaroslav Heyrovský
NomineesAllDFs_Long.loc[NomineesAllDFs_Long['Years_Nominated']=='1974'] #Tetsuo Nozoe

           Nominee Years_Nominated Country
2032  Tetsuo Nozoe            1974   Japan

**Observaciones**: Según [la página de los premios Nobel](https://www.nobelprize.org/prizes/chemistry/1959/heyrovsky/nominations/), Jaroslav Heyrovský fue nominado en 1934,1938,1940,1944,1947,1950,**1952,1953**,1954,1955,1956,1957,1958,1959. Por tanto, fue un error de tipeo de la [fuente 2](https://en.wikipedia.org/wiki/List_of_nominees_for_the_Nobel_Prize_in_Chemistry). Del mismo modo, solo se reporta que Tetsuo Nozoe fue nominado en 1970 y no en 1974.

In [1422]:
# Corrección de los datos
NomineesAllDFs.loc[NomineesAllDFs['Nominee']=='Jaroslav Heyrovský'] #row: 27
NomineesAllDFs.loc[27,'Years_Nominated']='1934,1938,1940,1944,1947,1950,1952,1953,1954,1955,1956,1957,1958,1959'

# Corrección de los datos
NomineesAllDFs.loc[NomineesAllDFs['Nominee']=='Tetsuo Nozoe'] #row: 30
NomineesAllDFs.loc[30,'Years_Nominated']='1970'

#Ordenando el DF por año (una fila para cada año de nominación)
NomineesAllDFs_Long=NomineesAllDFs.copy()
NomineesAllDFs_Long['Years_Nominated']=NomineesAllDFs_Long['Years_Nominated'].str.split(",")
NomineesAllDFs_Long=NomineesAllDFs_Long.explode('Years_Nominated')
NomineesAllDFs_Long.reset_index(drop=True,inplace=True)

#DF resultante
NomineesAllDFs_Long

                           Nominee Years_Nominated      Country
0     Jacobus Henricus van 't Hoff            1901  Netherlands
1                     Emil Fischer            1901      Germany
2                     Emil Fischer            1902      Germany
3                     Emil Fischer            1916      Germany
4                     Emil Fischer            1919      Germany
...                            ...             ...          ...
2034   Henry Montague (Monty) Frey            1958      England
2035   Henry Montague (Monty) Frey            1959      England
2036           Jack Sylvester Hine            1970   California
2037               Wolfgang Kirmse            1970      Germany
2038                  Tetsuo Nozoe            1970        Japan

[2039 rows x 3 columns]

In [1423]:
# Para realizar merge con las otras dos fuentes, se agruparán los nominados por año
Nominees_DF_2=NomineesAllDFs_Long.groupby(['Years_Nominated'],as_index=False).agg({'Country':'first','Nominee':lambda x : ' , '.join(x.astype(str))})
Nominees_DF_2['Years_Nominated']=Nominees_DF_2['Years_Nominated'].astype('int')
Nominees_DF_2=Nominees_DF_2.drop(columns='Country')
Nominees_DF_2=Nominees_DF_2.rename(columns={'Nominee':'Nominees'})

Nominees_DF_2

    Years_Nominated                                           Nominees
0              1901  Jacobus Henricus van 't Hoff , Emil Fischer , ...
1              1902  Emil Fischer , Svante Arrhenius , Henri Moissa...
2              1903  Svante Arrhenius , Henri Moissan , Marcellin B...
3              1904  Henri Moissan , Marcellin Berthelot , William ...
4              1905  Henri Moissan , Adolf von Baeyer , Theodore Wi...
..              ...                                                ...
65             1966  Christopher Kelk Ingold , Alexander Frumkin , ...
66             1967  Christopher Kelk Ingold , Alexander Frumkin , ...
67             1968  Christopher Kelk Ingold , Henry Eyring , Willi...
68             1969  Christopher Kelk Ingold , Walter Heitler , Hen...
69             1970  Paul Sabatier , Paul Walden , John Jacob Abel ...

[70 rows x 2 columns]

## c) Fuente 3

In [1424]:
import pandas as pd

AffiliationLink="https://en.wikipedia.org/wiki/List_of_Nobel_laureates_by_university_affiliation"
Affiliation=pd.read_html(AffiliationLink,header=0,flavor='bs4')
type(Affiliation)

list

In [1425]:
Affiliation[0]

,Laureate,Discipline,Year of award,Affiliation
0,Alexei Abrikosov,Physics,2003,Argonne National Laboratory
1,Edgar Adrian,Physiology or Medicine,1932,University of Cambridge
2,Pierre Agostini,Physics,2023,Ohio State University
3,Peter Agre,Chemistry,2003,Johns Hopkins School of Medicine
4,Isamu Akasaki,Physics,2014,Meijo University
...,...,...,...,...
806,Frits Zernike,Physics,1953,University of Groningen
807,Ahmed Zewail,Chemistry,1999,California Institute of Technology
808,Karl Ziegler,Chemistry,1963,Max Planck Institute for Coal Research
809,Rolf M. Zinkernagel,Physiology or Medicine,1996,University of Zurich
810,Richard Adolf Zsigmondy,Chemistry,1925,University of Göttingen

In [1426]:
Affiliation[0].columns

Index(['Laureate', 'Discipline', 'Year of award', 'Affiliation'], dtype='object')

In [1427]:
#Creando un DF con solo los ganadores al premio Nobel de Química
Affiliation_DF=Affiliation[0].loc[Affiliation[0]['Discipline']=='Chemistry']

#Eliminado la columna 'Discipline' del nuevo DF
Affiliation_DF.drop(columns=['Discipline'],inplace=True)

# Renombrando la columna "Year of award"
Affiliation_DF = Affiliation_DF.rename(columns={"Year of award":"Year_of_award"})
Affiliation_DF

C:\Users\Patiy Li Yang\AppData\Local\Temp\ipykernel_11844\356506548.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Affiliation_DF.drop(columns=['Discipline'],inplace=True)

,Laureate,Year_of_award,Affiliation
3,Peter Agre,2003,Johns Hopkins School of Medicine
7,Kurt Alder,1950,University of Cologne
14,Sidney Altman,1989,Yale University
19,Christian B. Anfinsen,1972,National Institutes of Health
23,Frances Arnold,2018,California Institute of Technology
...,...,...,...
798,Akira Yoshino,2019,Asahi Kasei
799,Akira Yoshino,2019,Meijo University
807,Ahmed Zewail,1999,California Institute of Technology
808,Karl Ziegler,1963,Max Planck Institute for Coal Research
810,Richard Adolf Zsigmondy,1925,University of Göttingen

In [1428]:
#Ordenando los datos de forma ascendente por año
Affiliation_DF.sort_values(by=['Year_of_award'], inplace=True)
Affiliation_DF.reset_index(inplace=True,drop=True)
Affiliation_DF

,Laureate,Year_of_award,Affiliation
0,Jacobus Henricus van 't Hoff,1901,Humboldt University of Berlin
1,Emil Fischer,1902,Humboldt University of Berlin
2,Svante Arrhenius,1903,Stockholm University
3,William Ramsay,1904,University College London
4,Adolf von Baeyer,1905,Ludwig Maximilian University of Munich
...,...,...,...
206,Carolyn Bertozzi,2022,Howard Hughes Medical Institute
207,Morten P. Meldal,2022,University of Copenhagen
208,Karl Barry Sharpless,2022,Scripps Research
209,Louis E. Brus,2023,Columbia University
210,Moungi Bawendi,2023,Massachusetts Institute of Technology

## d) Unión (merging) de los tres DFs

### d.1) Merge de Nominees_DF_2 y Laureates_DF

In [1429]:
Nominees_DF_2.info(), Laureates_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Years_Nominated  70 non-null     int32
 1   Nominees         70 non-null     object
dtypes: int32(1), object(1)
memory usage: 972.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year_of_award     202 non-null    int64
 1   Laureate          202 non-null    object
 2   Rationale         202 non-null    object
 3   Birth_year        202 non-null    object
 4   Death_year        202 non-null    object
 5   Country_of_birth  202 non-null    object
dtypes: int64(1), object(5)
memory usage: 9.6+ KB

(None, None)

In [1430]:
#Merging
Laureates_Nominees_DF=Nominees_DF_2.merge(Laureates_DF,how='right',left_on='Years_Nominated',right_on='Year_of_award')
Laureates_Nominees_DF.drop(columns={'Years_Nominated'}, inplace=True)
Laureates_Nominees_DF

,Nominees,Year_of_award,Laureate,Rationale,Birth_year,Death_year,Country_of_birth
0,"Jacobus Henricus van 't Hoff , Emil Fischer , ...",1901,Jacobus Henricus van 't Hoff,"""[for his] discovery of the laws of chemical d...",1852,1911,Netherlands
1,"Emil Fischer , Svante Arrhenius , Henri Moissa...",1902,Hermann Emil Fischer,"""[for] his work on sugar and purine syntheses""",1852,1919,Germany
2,"Svante Arrhenius , Henri Moissan , Marcellin B...",1903,Svante August Arrhenius,"""[for] his electrolytic theory of dissociation""",1859,1927,Sweden
3,"Henri Moissan , Marcellin Berthelot , William ...",1904,Sir William Ramsay,"""[for his] discovery of the inert gaseous elem...",1852,1916,United Kingdom
4,"Henri Moissan , Adolf von Baeyer , Theodore Wi...",1905,Adolf von Baeyer,"""[for] the advancement of organic chemistry an...",1835,1917,Germany
...,...,...,...,...,...,...,...
197,NaN,2022,Morten Meldal,"""for the development of click chemistry and bi...",1954,Alive,Denmark
198,NaN,2022,K. Barry Sharpless,"""for the development of click chemistry and bi...",1941,Alive,United States
199,NaN,2023,Moungi G. Bawendi,"""for the discovery and synthesis of quantum dots""",1961,Alive,United States
200,NaN,2023,Louis E. Brus,"""for the discovery and synthesis of quantum dots""",1943,Alive,United States
201,NaN,2023,Alexey Ekimov,"""for the discovery and synthesis of quantum dots""",1945,Alive,Russia

### d.2) Merge de Leaureates_Nominees_DF y Affiliation_DF

**Problema**: Revisando la [fuente 3](https://en.wikipedia.org/wiki/List_of_Nobel_laureates_by_university_affiliation), ciertos ganadores presentan más de una afiliación y se ha creado una extra fila para cada afiliación. Por tanto, se deberán borrar los duplicados en Affiliation_DF.

In [1431]:
Laureates_DF.info(), Affiliation_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year_of_award     202 non-null    int64
 1   Laureate          202 non-null    object
 2   Rationale         202 non-null    object
 3   Birth_year        202 non-null    object
 4   Death_year        202 non-null    object
 5   Country_of_birth  202 non-null    object
dtypes: int64(1), object(5)
memory usage: 9.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Laureate       211 non-null    object
 1   Year_of_award  211 non-null    int64
 2   Affiliation    211 non-null    object
dtypes: int64(1), object(2)
memory usage: 5.1+ KB

(None, None)

In [1432]:
# Filas donde se observan duplicados en las columnas 'Laureate' y 'Year_Won'
Affiliation_DF[Affiliation_DF.duplicated(['Laureate','Year_of_award'],keep=False)]

#Notar que se ha seleccionado ambas columnas, pues Frederick Sanger y 	Karl Barry Sharpless han ganado el premio Nobel en años distintos

,Laureate,Year_of_award,Affiliation
28,Carl Bosch,1931,Heidelberg University
29,Friedrich Bergius,1931,Heidelberg University
30,Carl Bosch,1931,IG Farben
31,Friedrich Bergius,1931,IG Farben
36,Peter Debye,1936,Humboldt University of Berlin
37,Peter Debye,1936,Max Planck Institute for Physics
40,Richard Kuhn,1938,Heidelberg University
41,Richard Kuhn,1938,Max Planck Institute for Medical Research
42,Adolf Butenandt,1939,Max Planck Institute of Biochemistry
43,Adolf Butenandt,1939,Humboldt University of Berlin
64,Nikolay Semyonov,1956,Moscow State University
65,Nikolay Semyonov,1956,Institute for Chemical Physics of the Academy ...
94,Ilya Prigogine,1977,University of Texas at Austin
95,Ilya Prigogine,1977,Université libre de Bruxelles
113,Jean-Marie Lehn,1987,Louis Pasteur University
115,Jean-Marie Lehn,1987,Collège de France
116,Johann Deisenhofer,1988,University of Texas Southwestern Medical Center
117,Johann Deisenhofer,1988,Howard Hughes Medical Institute
144,Kurt Wüthrich,2002,Scripps Research
147,Kurt Wüthrich,2002,ETH Zurich
149,Roderick MacKinnon,2003,Howard Hughes Medical Institute
150,Roderick MacKinnon,2003,Rockefeller University
159,Roger Y. Tsien,2008,"University of California, San Diego"
161,Osamu Shimomura,2008,Boston University School of Medicine
162,Osamu Shimomura,2008,Marine Biological Laboratory
163,Roger Y. Tsien,2008,Howard Hughes Medical Institute
164,Thomas A. Steitz,2009,Howard Hughes Medical Institute
166,Thomas A. Steitz,2009,Yale University
172,Robert Lefkowitz,2012,Duke University Medical Center
173,Robert Lefkowitz,2012,Howard Hughes Medical Institute
175,Martin Karplus,2013,University of Strasbourg
176,Martin Karplus,2013,Harvard University
181,Stefan Hell,2014,Max Planck Institute for Biophysical Chemistry
182,Stefan Hell,2014,German Cancer Research Center
183,Paul L. Modrich,2015,Howard Hughes Medical Institute
185,Paul L. Modrich,2015,Duke University School of Medicine
186,Tomas Lindahl,2015,Francis Crick Institute
187,Tomas Lindahl,2015,Clare Hall laboratories
198,Akira Yoshino,2019,Asahi Kasei
199,Akira Yoshino,2019,Meijo University
205,Carolyn Bertozzi,2022,Stanford University
206,Carolyn Bertozzi,2022,Howard Hughes Medical Institute

In [1433]:
# Agrupación de las filas correspondienets al mismo ganador por año, agrupando las afiliaciones por comas en la tercera columna
Affiliation_DF=Affiliation_DF.groupby(['Laureate','Year_of_award'],as_index=False).agg({'Year_of_award':'first','Affiliation':lambda x : ','.join(x.astype(str))})

#Ordenando los datos de forma ascendente por año
Affiliation_DF.sort_values(by=['Year_of_award'], inplace=True)
Affiliation_DF.reset_index(inplace=True,drop=True)
Affiliation_DF

,Laureate,Year_of_award,Affiliation
0,Jacobus Henricus van 't Hoff,1901,Humboldt University of Berlin
1,Emil Fischer,1902,Humboldt University of Berlin
2,Svante Arrhenius,1903,Stockholm University
3,William Ramsay,1904,University College London
4,Adolf von Baeyer,1905,Ludwig Maximilian University of Munich
...,...,...,...
185,Carolyn Bertozzi,2022,"Stanford University,Howard Hughes Medical Inst..."
186,Morten P. Meldal,2022,University of Copenhagen
187,Karl Barry Sharpless,2022,Scripps Research
188,Louis E. Brus,2023,Columbia University
189,Moungi Bawendi,2023,Massachusetts Institute of Technology

In [1434]:
# Revisando nuevamente los duplicados: Se han logrado corregir satisfactoriamente 
Affiliation_DF[Affiliation_DF.duplicated(['Laureate','Year_of_award'],keep=False)]

Empty DataFrame
Columns: [Laureate, Year_of_award, Affiliation]
Index: []

**Problema 2**: Se busca unir Affiliation_DF y Laureates_DF mediante la columna en común 'Laureate'. Sin embargo, los nombres no se encuentran escritos en el mismo formato, por lo que se deberá realizar un fuzzy merge.

In [1435]:
# los nombres no se encuentran en el mismo formato, por lo que se deberá realizar un fuzzy merge
Laureates_Nominees_DF.Laureate=Laureates_Nominees_DF.Laureate.str.strip()
Affiliation_DF.Laureate=Affiliation_DF.Laureate.str.strip()

Laureates_Nominees_set=set(Laureates_Nominees_DF.Laureate)
Affiliation_set=set(Affiliation_DF.Laureate)

# Tomar un nombre en Affiliation_set y buscar el más similar en Laureates_set
from thefuzz import process as fz
[(f,fz.extractOne(f,Laureates_Nominees_set)) for f in sorted(Affiliation_set)
   if fz.extractOne(f,Laureates_Nominees_set)[1]>86]

[('Aaron Ciechanover', ('Aaron Ciechanover', 100)),
 ('Aaron Klug', ('Aaron Klug', 100)),
 ('Ada Yonath', ('Ada E. Yonath', 95)),
 ('Adolf von Baeyer', ('Adolf von Baeyer', 100)),
 ('Ahmed Zewail', ('Ahmed Zewail', 100)),
 ('Akira Suzuki', ('Akira Suzuki', 100)),
 ('Akira Yoshino', ('Akira Yoshino', 100)),
 ('Alan J. Heeger', ('Alan J. Heeger', 100)),
 ('Alan MacDiarmid', ('Alan G. MacDiarmid', 95)),
 ('Alexander R. Todd', ('Lord (Alexander R.) Todd', 95)),
 ('Alfred Werner', ('Alfred Werner', 100)),
 ('Arieh Warshel', ('Arieh Warshel', 100)),
 ('Arthur Harden', ('Arthur Harden', 100)),
 ('Artturi Ilmari Virtanen', ('Artturi Ilmari Virtanen', 100)),
 ('Avram Hershko', ('Avram Hershko', 100)),
 ('Aziz Sancar', ('Aziz Sancar', 100)),
 ('Ben Feringa', ('Ben Feringa', 100)),
 ('Benjamin List', ('Benjamin List', 100)),
 ('Brian Kobilka', ('Brian Kobilka', 100)),
 ('Carl Bosch', ('Carl Bosch', 100)),
 ('Carolyn Bertozzi', ('Carolyn Bertozzi', 100)),
 ('Charles J. Pedersen', ('Charles J. Pedersen', 100)),
 ('Christian B. Anfinsen', ('Christian B. Anfinsen', 100)),
 ('Cyril Norman Hinshelwood', ('Sir Cyril Norman Hinshelwood', 95)),
 ('Dan Shechtman', ('Dan Shechtman', 100)),
 ('David MacMillan', ('David W.C. MacMillan', 95)),
 ('Donald J. Cram', ('Donald J. Cram', 100)),
 ('Dudley R. Herschbach', ('Dudley R. Herschbach', 100)),
 ('Eduard Buchner', ('Eduard Buchner', 100)),
 ('Ei-ichi Negishi', ('Ei-ichi Negishi', 100)),
 ('Elias James Corey', ('Elias James Corey', 100)),
 ('Emil Fischer', ('Hermann Emil Fischer', 90)),
 ('Emmanuelle Charpentier', ('Emmanuelle Charpentier', 100)),
 ('Eric Betzig', ('Eric Betzig', 100)),
 ('Ernest Rutherford', ('Ernest Rutherford', 100)),
 ('Ernst Otto Fischer', ('Ernst Otto Fischer', 100)),
 ('F. Sherwood Rowland', ('Frank Sherwood Rowland', 89)),
 ('Frances Arnold', ('Frances Arnold', 100)),
 ('Francis William Aston', ('Francis William Aston', 100)),
 ('Fraser Stoddart', ('Fraser Stoddart', 100)),
 ('Frederick Sanger', ('Frederick Sanger', 100)),
 ('Frederick Soddy', ('Frederick Soddy', 100)),
 ('Friedrich Bergius', ('Friedrich Bergius', 100)),
 ('Fritz Haber', ('Fritz Haber', 100)),
 ('Fritz Pregl', ('Fritz Pregl', 100)),
 ('Frédéric Joliot-Curie', ('Frédéric Joliot', 95)),
 ('Geoffrey Wilkinson', ('Geoffrey Wilkinson', 100)),
 ('Georg Wittig', ('Georg Wittig', 100)),
 ('George Andrew Olah', ('George A. Olah', 87)),
 ('George P. Smith', ('George Smith', 95)),
 ('George de Hevesy', ('George de Hevesy', 100)),
 ('Gerhard Ertl', ('Gerhard Ertl', 100)),
 ('Gerhard Herzberg', ('Gerhard Herzberg', 100)),
 ('Giulio Natta', ('Giulio Natta', 100)),
 ('Glenn T. Seaborg', ('Glenn Theodore Seaborg', 88)),
 ('Gregory Winter', ('Sir Gregory Winter', 95)),
 ('Hans Fischer', ('Hans Fischer', 100)),
 ('Hartmut Michel', ('Hartmut Michel', 100)),
 ('Heinrich Otto Wieland', ('Heinrich Otto Wieland', 100)),
 ('Henri Moissan', ('Henri Moissan', 100)),
 ('Henry Taube', ('Henry Taube', 100)),
 ('Herbert A. Hauptman', ('Herbert A. Hauptman', 100)),
 ('Herbert C. Brown', ('Herbert C. Brown', 100)),
 ('Hermann Staudinger', ('Hermann Staudinger', 100)),
 ('Hideki Shirakawa', ('Hideki Shirakawa', 100)),
 ('Ilya Prigogine', ('Ilya Prigogine', 100)),
 ('Irving Langmuir', ('Irving Langmuir', 100)),
 ('Irwin Rose', ('Irwin Rose', 100)),
 ('Irène Joliot-Curie', ('Irène Joliot-Curie', 100)),
 ("Jacobus Henricus van 't Hoff", ("Jacobus Henricus van 't Hoff", 100)),
 ('Jacques Dubochet', ('Jacques Dubochet', 100)),
 ('Jaroslav Heyrovský', ('Jaroslav Heyrovský', 100)),
 ('Jean-Marie Lehn', ('Jean-Marie Lehn', 100)),
 ('Jean-Pierre Sauvage', ('Jean-Pierre Sauvage', 100)),
 ('Jennifer Doudna', ('Jennifer Doudna', 100)),
 ('Jerome Karle', ('Jerome Karle', 100)),
 ('Joachim Frank', ('Joachim Frank', 100)),
 ('Johann Deisenhofer', ('Johann Deisenhofer', 100)),
 ('John B. Fenn', ('John B. Fenn', 100)),
 ('John B. Goodenough', ('John B. Goodenough', 100)),
 ('John E. Walker', ('John E. Walker', 100)),
 ('John Howard Northrop', ('John Howard Northrop', 100)),
 ('John Polanyi', ('John C. Polanyi', 95)),
 ('John Pople', ('John A. Pople', 95)),
 ('Karl Barry Sharpless', ('K. Barry Sharpless', 89)),
 ('Karl Ziegler', ('Karl Ziegler', 100)),
 ('Kenichi Fukui', ('Kenichi Fukui', 100)),
 ('Koichi Tanaka', ('Koichi Tanaka', 100)),
 ('Kurt Alder', ('Kurt Alder', 100)),
 ('Kurt Wüthrich', ('Kurt Wüthrich', 100)),
 ('Lars Onsager', ('Lars Onsager', 100)),
 ('Leopold Ružička', ('Leopold Ružička', 100)),
 ('Linus Pauling', ('Linus Pauling', 100)),
 ('Louis E. Brus', ('Louis E. Brus', 100)),
 ('Luis Federico Leloir', ('Luis F. Leloir', 87)),
 ('M. Stanley Whittingham', ('M. Stanley Whittingham', 100)),
 ('Manfred Eigen', ('Manfred Eigen', 100)),
 ('Marie Curie', ('Marie Curie, née Skłodowska', 90)),
 ('Mario Molina', ('Mario J. Molina', 95)),
 ('Martin Chalfie', ('Martin Chalfie', 100)),
 ('Martin Karplus', ('Martin Karplus', 100)),
 ('Melvin Calvin', ('Melvin Calvin', 100)),
 ('Michael Levitt', ('Michael Levitt', 100)),
 ('Michael Smith', ('Michael Smith', 100)),
 ('Morten P. Meldal', ('Morten Meldal', 95)),
 ('Moungi Bawendi', ('Moungi G. Bawendi', 95)),
 ('Norman Haworth', ('Walter Norman Haworth', 90)),
 ('Odd Hassel', ('Odd Hassel', 100)),
 ('Osamu Shimomura', ('Osamu Shimomura', 100)),
 ('Otto Hahn', ('Otto Hahn', 100)),
 ('Otto Wallach', ('Otto Wallach', 100)),
 ('Paul Berg', ('Paul Berg', 100)),
 ('Paul D. Boyer', ('Paul D. Boyer', 100)),
 ('Paul Flory', ('Paul J. Flory', 95)),
 ('Paul J. Crutzen', ('Paul J. Crutzen', 100)),
 ('Paul Karrer', ('Paul Karrer', 100)),
 ('Paul L. Modrich', ('Paul L. Modrich', 100)),
 ('Paul Sabatier', ('Paul Sabatier', 100)),
 ('Peter Agre', ('Peter Agre', 100)),
 ('Peter D. Mitchell', ('Peter D. Mitchell', 100)),
 ('Peter Debye', ('Peter Debye', 100)),
 ('Richard Adolf Zsigmondy', ('Richard Adolf Zsigmondy', 100)),
 ('Richard F. Heck', ('Richard F. Heck', 100)),
 ('Richard Henderson', ('Richard Henderson', 100)),
 ('Richard Kuhn', ('Richard Kuhn', 100)),
 ('Richard Laurence Millington Synge',
  ('Richard Laurence Millington Synge', 100)),
 ('Richard R. Ernst', ('Richard R. Ernst', 100)),
 ('Richard R. Schrock', ('Richard R. Schrock', 100)),
 ('Richard Smalley', ('Richard E. Smalley', 95)),
 ('Richard Willstätter', ('Richard Martin Willstätter', 95)),
 ('Roald Hoffmann', ('Roald Hoffmann', 100)),
 ('Robert Bruce Merrifield', ('Robert Bruce Merrifield', 100)),
 ('Robert Burns Woodward', ('Robert Burns Woodward', 100)),
 ('Robert H. Grubbs', ('Robert H. Grubbs', 100)),
 ('Robert Huber', ('Robert Huber', 100)),
 ('Robert Lefkowitz', ('Robert Lefkowitz', 100)),
 ('Robert Robinson', ('Sir Robert Robinson', 95)),
 ('Robert S. Mulliken', ('Robert S. Mulliken', 100)),
 ('Roderick MacKinnon', ('Roderick MacKinnon', 100)),
 ('Roger D. Kornberg', ('Roger D. Kornberg', 100)),
 ('Roger Y. Tsien', ('Roger Y. Tsien', 100)),
 ('Ronald George Wreyford Norrish', ('Ronald George Wreyford Norrish', 100)),
 ('Rudolph A. Marcus', ('Rudolph A. Marcus', 100)),
 ('Ryōji Noyori', ('Ryōji Noyori', 100)),
 ('Sidney Altman', ('Sidney Altman', 100)),
 ('Stanford Moore', ('Stanford Moore', 100)),
 ('Stefan Hell', ('Stefan W. Hell', 95)),
 ('Svante Arrhenius', ('Svante August Arrhenius', 95)),
 ('Theodor Svedberg', ('The (Theodor) Svedberg', 95)),
 ('Theodore William Richards', ('Theodore William Richards', 100)),
 ('Thomas A. Steitz', ('Thomas A. Steitz', 100)),
 ('Thomas Cech', ('Thomas Cech', 100)),
 ('Tomas Lindahl', ('Tomas Lindahl', 100)),
 ('Victor Grignard', ('Victor Grignard', 100)),
 ('Vincent du Vigneaud', ('Vincent du Vigneaud', 100)),
 ('Vladimir Prelog', ('Vladimir Prelog', 100)),
 ('Walter Gilbert', ('Walter Gilbert', 100)),
 ('Walter Kohn', ('Walter Kohn', 100)),
 ('Wendell Meredith Stanley', ('Wendell Meredith Stanley', 100)),
 ('Wilhelm Ostwald', ('Wilhelm Ostwald', 100)),
 ('Willard Libby', ('Willard Frank Libby', 95)),
 ('William E. Moerner', ('William E. Moerner', 100)),
 ('William Howard Stein', ('William H. Stein', 88)),
 ('William Lipscomb', ('William N. Lipscomb', 95)),
 ('William Ramsay', ('Sir William Ramsay', 95)),
 ('Yuan T. Lee', ('Yuan T. Lee', 100)),
 ('Yves Chauvin', ('Yves Chauvin', 100))]

In [1436]:
# Cambiando los nombres de los ganadores de la columna 'Laureate' en Affiliation_DF 
changesAff_Laureate={f:fz.extractOne(f,Laureates_Nominees_set)[0] for f in sorted(Affiliation_set)
   if fz.extractOne(f,Laureates_Nominees_set)[1]>86}

Affiliation_DF.Laureate.replace(to_replace=changesAff_Laureate,inplace=True)
Affiliation_DF

,Laureate,Year_of_award,Affiliation
0,Jacobus Henricus van 't Hoff,1901,Humboldt University of Berlin
1,Hermann Emil Fischer,1902,Humboldt University of Berlin
2,Svante August Arrhenius,1903,Stockholm University
3,Sir William Ramsay,1904,University College London
4,Adolf von Baeyer,1905,Ludwig Maximilian University of Munich
...,...,...,...
185,Carolyn Bertozzi,2022,"Stanford University,Howard Hughes Medical Inst..."
186,Morten Meldal,2022,University of Copenhagen
187,K. Barry Sharpless,2022,Scripps Research
188,Louis E. Brus,2023,Columbia University
189,Moungi G. Bawendi,2023,Massachusetts Institute of Technology

In [1437]:
#Nombres faltantes
# Nota: Affiliation_DF tiene 190 filas y Laureates_Nominees_DF, 194 (no hay información de afiliación de todos los ganadores)
Laureates_Nominees_set=set(Laureates_Nominees_DF.Laureate)
Affiliation_set2=set(Affiliation_DF.Laureate)

{f:fz.extractOne(f,Laureates_Nominees_set)[0] for f in sorted(Affiliation_set)
   if fz.extractOne(f,Laureates_Nominees_set)[1]<=86}

{'Adolf Butenandt': 'Adolf Otto Reinhold Windaus',
 'Adolf Windaus': 'Adolf Otto Reinhold Windaus',
 'Archer Martin': 'Archer John Porter Martin',
 'Arne Tiselius': 'Arne Wilhelm Kaurin Tiselius',
 'Derek Barton': 'Derek H. R. Barton',
 'Dorothy Hodgkin': 'Dorothy Crowfoot Hodgkin',
 'Edwin McMillan': 'Edwin Mattison McMillan',
 'Hans von Euler-Chelpin': 'Hans Fischer',
 'Harold Urey': 'Sir Harold W. Kroto',
 'Harry Kroto': 'Sir Harold W. Kroto',
 'James B. Sumner': 'James Batcheller Sumner',
 'Jens Christian Skou': 'Jens C. Skou',
 'John Cornforth': 'Archer John Porter Martin',
 'John Kendrew': 'John Cowdery Kendrew',
 'Max Perutz': 'Max Ferdinand Perutz',
 'Nikolay Semyonov': 'Nikolay Nikolaevich Semenov',
 'Otto Diels': 'Otto Paul Hermann Diels',
 'Robert Curl': 'Robert Bruce Merrifield',
 'Venki Ramakrishnan': 'Venkatraman Ramakrishnan',
 'Walther Nernst': 'Walther Hermann Nernst',
 'William Giauque': 'Theodore William Richards'}

In [1438]:
# Corrigiendo manualmente los nombres faltantes (hay errores en algunos resultados y estos han sido señalados)
changesAff_Laureate2= {'Adolf Butenandt': 'Adolf Friedrich Johann Butenandt', #corrección
 'Adolf Windaus': 'Adolf Otto Reinhold Windaus',
 'Archer Martin': 'Archer John Porter Martin',
 'Arne Tiselius': 'Arne Wilhelm Kaurin Tiselius',
 'Derek Barton': 'Derek H. R. Barton',
 'Dorothy Hodgkin': 'Dorothy Crowfoot Hodgkin',
 'Edwin McMillan': 'Edwin Mattison McMillan',
 'Hans von Euler-Chelpin': 'Hans Karl August Simon von Euler-Chelpin', #corrección
 'Harold Urey': 'Harold Clayton Urey', #corrección
 'Harry Kroto': 'Sir Harold W. Kroto',
 'James B. Sumner': 'James Batcheller Sumner',
 'Jens Christian Skou': 'Jens C. Skou',
 'John Cornforth': 'John Warcup Cornforth', #corrección
 'John Kendrew': 'John Cowdery Kendrew',
 'Max Perutz': 'Max Ferdinand Perutz',
 'Nikolay Semyonov': 'Nikolay Nikolaevich Semenov',
 'Otto Diels': 'Otto Paul Hermann Diels',
 'Robert Curl': 'Robert F. Curl Jr.', #corrección
 'Venki Ramakrishnan': 'Venkatraman Ramakrishnan',
 'Walther Nernst': 'Walther Hermann Nernst',
 'William Giauque': 'William Francis Giauque'} #corrección

Affiliation_DF.Laureate.replace(to_replace=changesAff_Laureate2,inplace=True)
Affiliation_DF

,Laureate,Year_of_award,Affiliation
0,Jacobus Henricus van 't Hoff,1901,Humboldt University of Berlin
1,Hermann Emil Fischer,1902,Humboldt University of Berlin
2,Svante August Arrhenius,1903,Stockholm University
3,Sir William Ramsay,1904,University College London
4,Adolf von Baeyer,1905,Ludwig Maximilian University of Munich
...,...,...,...
185,Carolyn Bertozzi,2022,"Stanford University,Howard Hughes Medical Inst..."
186,Morten Meldal,2022,University of Copenhagen
187,K. Barry Sharpless,2022,Scripps Research
188,Louis E. Brus,2023,Columbia University
189,Moungi G. Bawendi,2023,Massachusetts Institute of Technology

In [1439]:
# Verificando que todos los nombres hayan sido reemplazados con sus análogos
Laureates_Nominees_set=set(Laureates_Nominees_DF.Laureate)
Affiliation_set3=set(Affiliation_DF.Laureate)

Affiliation_set3-Laureates_Nominees_set  # Ya se han reemplazado todos

set()

In [1440]:
Affiliation_DF.info(),Laureates_Nominees_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Laureate       190 non-null    object
 1   Year_of_award  190 non-null    int64
 2   Affiliation    190 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nominees          87 non-null     object
 1   Year_of_award     202 non-null    int64
 2   Laureate          202 non-null    object
 3   Rationale         202 non-null    object
 4   Birth_year        202 non-null    object
 5   Death_year        202 non-null    object
 6   Country_of_birth  202 non-null    object
dtypes: int64(1), object(6)
memory usage: 11.2+ KB

(None, None)

In [1441]:
# Finalmente: Merging
Laureates_Nominees_Affiliation_DF=Affiliation_DF.merge(Laureates_Nominees_DF,how='right',left_on='Laureate',right_on='Laureate')
Laureates_Nominees_Affiliation_DF

,Laureate,Year_of_award_x,Affiliation,Nominees,Year_of_award_y,Rationale,Birth_year,Death_year,Country_of_birth
0,Jacobus Henricus van 't Hoff,1901.0,Humboldt University of Berlin,"Jacobus Henricus van 't Hoff , Emil Fischer , ...",1901,"""[for his] discovery of the laws of chemical d...",1852,1911,Netherlands
1,Hermann Emil Fischer,1902.0,Humboldt University of Berlin,"Emil Fischer , Svante Arrhenius , Henri Moissa...",1902,"""[for] his work on sugar and purine syntheses""",1852,1919,Germany
2,Svante August Arrhenius,1903.0,Stockholm University,"Svante Arrhenius , Henri Moissan , Marcellin B...",1903,"""[for] his electrolytic theory of dissociation""",1859,1927,Sweden
3,Sir William Ramsay,1904.0,University College London,"Henri Moissan , Marcellin Berthelot , William ...",1904,"""[for his] discovery of the inert gaseous elem...",1852,1916,United Kingdom
4,Adolf von Baeyer,1905.0,Ludwig Maximilian University of Munich,"Henri Moissan , Adolf von Baeyer , Theodore Wi...",1905,"""[for] the advancement of organic chemistry an...",1835,1917,Germany
...,...,...,...,...,...,...,...,...,...
201,K. Barry Sharpless,2001.0,Scripps Research,NaN,2022,"""for the development of click chemistry and bi...",1941,Alive,United States
202,K. Barry Sharpless,2022.0,Scripps Research,NaN,2022,"""for the development of click chemistry and bi...",1941,Alive,United States
203,Moungi G. Bawendi,2023.0,Massachusetts Institute of Technology,NaN,2023,"""for the discovery and synthesis of quantum dots""",1961,Alive,United States
204,Louis E. Brus,2023.0,Columbia University,NaN,2023,"""for the discovery and synthesis of quantum dots""",1943,Alive,United States
205,Alexey Ekimov,NaN,NaN,NaN,2023,"""for the discovery and synthesis of quantum dots""",1945,Alive,Russia

In [1442]:
Laureates_Nominees_Affiliation_DF=Affiliation_DF.merge(Laureates_Nominees_DF,how='right',left_on='Laureate',right_on='Laureate')

#Limpiando el DF resultante
Laureates_Nominees_Affiliation_DF.drop(columns='Year_of_award_x', inplace=True)
Laureates_Nominees_Affiliation_DF=Laureates_Nominees_Affiliation_DF.rename(columns={'Year_of_award_y':'Year_of_award'})

#Ordenando columnas
Laureates_Nominees_Affiliation_DF=Laureates_Nominees_Affiliation_DF.reindex(columns=['Year_of_award','Nominees','Laureate','Birth_year','Death_year','Affiliation','Rationale','Country_of_birth'])
Laureates_Nominees_Affiliation_DF

,Year_of_award,Nominees,Laureate,Birth_year,Death_year,Affiliation,Rationale,Country_of_birth
0,1901,"Jacobus Henricus van 't Hoff , Emil Fischer , ...",Jacobus Henricus van 't Hoff,1852,1911,Humboldt University of Berlin,"""[for his] discovery of the laws of chemical d...",Netherlands
1,1902,"Emil Fischer , Svante Arrhenius , Henri Moissa...",Hermann Emil Fischer,1852,1919,Humboldt University of Berlin,"""[for] his work on sugar and purine syntheses""",Germany
2,1903,"Svante Arrhenius , Henri Moissan , Marcellin B...",Svante August Arrhenius,1859,1927,Stockholm University,"""[for] his electrolytic theory of dissociation""",Sweden
3,1904,"Henri Moissan , Marcellin Berthelot , William ...",Sir William Ramsay,1852,1916,University College London,"""[for his] discovery of the inert gaseous elem...",United Kingdom
4,1905,"Henri Moissan , Adolf von Baeyer , Theodore Wi...",Adolf von Baeyer,1835,1917,Ludwig Maximilian University of Munich,"""[for] the advancement of organic chemistry an...",Germany
...,...,...,...,...,...,...,...,...
201,2022,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for the development of click chemistry and bi...",United States
202,2022,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for the development of click chemistry and bi...",United States
203,2023,NaN,Moungi G. Bawendi,1961,Alive,Massachusetts Institute of Technology,"""for the discovery and synthesis of quantum dots""",United States
204,2023,NaN,Louis E. Brus,1943,Alive,Columbia University,"""for the discovery and synthesis of quantum dots""",United States
205,2023,NaN,Alexey Ekimov,1945,Alive,NaN,"""for the discovery and synthesis of quantum dots""",Russia

In [1443]:
#Revisando si hay duplicados en ciertas filas
Laureates_Nominees_Affiliation_DF[Laureates_Nominees_Affiliation_DF.duplicated(['Laureate','Year_of_award'],keep=False)]

C:\Users\Patiy Li Yang\anaconda3\envs\Ciencia_de_datos_espaciales\Lib\site-packages\IPython\core\displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

,Year_of_award,Nominees,Laureate,Birth_year,Death_year,Affiliation,Rationale,Country_of_birth
69,1958,"Walther Nernst , Otto Hahn , Lise Meitner , Pa...",Frederick Sanger,1918,2013,University of Cambridge,"""for his work on the structure of proteins, es...",United Kingdom
70,1958,"Walther Nernst , Otto Hahn , Lise Meitner , Pa...",Frederick Sanger,1918,2013,MRC Laboratory of Molecular Biology,"""for his work on the structure of proteins, es...",United Kingdom
104,1980,NaN,Frederick Sanger,1918,2013,University of Cambridge,"""for their contributions concerning the determ...",United Kingdom
105,1980,NaN,Frederick Sanger,1918,2013,MRC Laboratory of Molecular Biology,"""for their contributions concerning the determ...",United Kingdom
147,2001,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for his work on chirally catalysed oxidation ...",United States
148,2001,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for his work on chirally catalysed oxidation ...",United States
201,2022,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for the development of click chemistry and bi...",United States
202,2022,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for the development of click chemistry and bi...",United States

In [1444]:
# Eliminando una de las filas duplicadas
Laureates_Nominees_Affiliation_DF.drop([70,105,148,202],axis=0, inplace = True)
Laureates_Nominees_Affiliation_DF.reset_index(inplace=True,drop=True)

#Resultado
Laureates_Nominees_Affiliation_DF

,Year_of_award,Nominees,Laureate,Birth_year,Death_year,Affiliation,Rationale,Country_of_birth
0,1901,"Jacobus Henricus van 't Hoff , Emil Fischer , ...",Jacobus Henricus van 't Hoff,1852,1911,Humboldt University of Berlin,"""[for his] discovery of the laws of chemical d...",Netherlands
1,1902,"Emil Fischer , Svante Arrhenius , Henri Moissa...",Hermann Emil Fischer,1852,1919,Humboldt University of Berlin,"""[for] his work on sugar and purine syntheses""",Germany
2,1903,"Svante Arrhenius , Henri Moissan , Marcellin B...",Svante August Arrhenius,1859,1927,Stockholm University,"""[for] his electrolytic theory of dissociation""",Sweden
3,1904,"Henri Moissan , Marcellin Berthelot , William ...",Sir William Ramsay,1852,1916,University College London,"""[for his] discovery of the inert gaseous elem...",United Kingdom
4,1905,"Henri Moissan , Adolf von Baeyer , Theodore Wi...",Adolf von Baeyer,1835,1917,Ludwig Maximilian University of Munich,"""[for] the advancement of organic chemistry an...",Germany
...,...,...,...,...,...,...,...,...
197,2022,NaN,Morten Meldal,1954,Alive,University of Copenhagen,"""for the development of click chemistry and bi...",Denmark
198,2022,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for the development of click chemistry and bi...",United States
199,2023,NaN,Moungi G. Bawendi,1961,Alive,Massachusetts Institute of Technology,"""for the discovery and synthesis of quantum dots""",United States
200,2023,NaN,Louis E. Brus,1943,Alive,Columbia University,"""for the discovery and synthesis of quantum dots""",United States
201,2023,NaN,Alexey Ekimov,1945,Alive,NaN,"""for the discovery and synthesis of quantum dots""",Russia

In [1445]:
#Revisando nuevamente si hay duplicados en ciertas filas: No hay
Laureates_Nominees_Affiliation_DF[Laureates_Nominees_Affiliation_DF.duplicated(['Laureate','Year_of_award'],keep=False)]

Empty DataFrame
Columns: [Year_of_award, Nominees, Laureate, Birth_year, Death_year, Affiliation, Rationale, Country_of_birth]
Index: []

## d) Unión (merging) de Laureates_Nominees_Affiliation_DF con el archivo adjunto

In [1446]:
Nobel_Chemistry_DF=Laureates_Nominees_Affiliation_DF.copy()

country_isos=pd.read_excel('https://github.com/Ciencia-de-datos-espaciales-2023-2/Ejercicio_2/raw/main/country_isos.xlsx')
country_isos

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
1,ALBANIA,The Republic of Albania,.al,AL,ALB
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,ANGOLA,The Republic of Angola,.ao,AO,AGO
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG
...,...,...,...,...,...
166,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
167,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
168,YEMEN,The Republic of Yemen,.ye,YE,YEM
169,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
170,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [1447]:
# Fuzzy merge de los nombres de los países de Nobel_Chemistry_DF y country_isos
Nobel_Chemistry_DF_set=set(Nobel_Chemistry_DF.Country_of_birth)
country_isos_set=set(country_isos.Country)

# Tomar un nombre en Nobel_Chemistry_DF_set y buscar el más similar en country_isos_set
from thefuzz import process as fz
[(f,fz.extractOne(f,country_isos_set)) for f in sorted(Nobel_Chemistry_DF_set)
   if fz.extractOne(f,country_isos_set)[1]>=95]

# Cambiando los nombres de los países de nacimiento en Nobel_Chemistry_DF
changes_Country={f:fz.extractOne(f,country_isos_set)[0] for f in sorted(Nobel_Chemistry_DF_set)
   if fz.extractOne(f,country_isos_set)[1]>=95}

Nobel_Chemistry_DF.replace(to_replace=changes_Country,inplace=True)

In [1448]:
# Nombres faltantes
Nobel_Chemistry_DF_set=set(Nobel_Chemistry_DF.Country_of_birth)
country_isos_set=set(country_isos.Country)

# Tomar un nombre en Nobel_Chemistry_DF_set y buscar el más similar en country_isos_set
from thefuzz import process as fz
changes_Country2={f:fz.extractOne(f,country_isos_set)[0] for f in sorted(Nobel_Chemistry_DF_set)
   if fz.extractOne(f,country_isos_set)[1]<95}

changes_Country2

{'Czechoslovakia': 'SLOVAKIA',
 'Israel': 'IRAQ',
 'Kingdom of Yugoslavia': 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
 'Not awarded': 'QATAR',
 'Russia': 'RUSSIAN FEDERATION (THE)',
 'Soviet Union': 'VIET NAM',
 'United Kingdom': 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
 'United States': 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
 'West Germany': 'GERMANY',
 'Yugoslavia': 'LATVIA'}

In [1449]:
# Algunos países tienen que reescribirse manualmebte, porque algunos ya no existen (ejm: Yugoslavia,Czechoslovakia)
# Se han señalado las que se han corregido a mano
changes_Country3= {
    'Czechoslovakia': 'CZECHIA', #corrección: Czechoslovakia es actualmente un territorio que comprende República Checa y eslovakia, pero Jaroslav Heyrovský nació en Praga, perteneciente a República Checa
 'Israel': 'ISRAEL', #NOTA: Israel no se encuentra en el el archivo adjunto
 'Kingdom of Yugoslavia': 'CROATIA', # corrección Leopold Ružička nació en Vukovar, Yugoslavia (actual CROACIA)
 'Not awarded': 'Not awarded', #corrección
 'Russia': 'RUSSIAN FEDERATION (THE)',
 'Soviet Union': 'RUSSIAN FEDERATION (THE)', #corrección: Nikolay Nikolaevich Semenov nació en Saratov Oblast, Russia (antigua Unión Soviética)
 'United Kingdom': 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
 'United States': 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
 'West Germany': 'GERMANY', 
 'Yugoslavia': 'BOSNIA AND HERZEGOVINA'} #corrección: Vladimir Prelog nació en  Sarajevo, Yugoslavia (actual Bosnia y Hersegovina)

Nobel_Chemistry_DF.replace(to_replace=changes_Country3,inplace=True)

In [1460]:
# Merging
Nobel_Chemistry_countryisos_DF=Nobel_Chemistry_DF.merge(country_isos,how='left',right_on='Country',left_on='Country_of_birth')
Nobel_Chemistry_countryisos_DF.drop(columns={'Country'}, inplace=True)

#Resultado final
Nobel_Chemistry_countryisos_DF.to_csv("Nobel_Chemistry_countryisos_DF.csv")
Nobel_Chemistry_countryisos_DF

,Year_of_award,Nominees,Laureate,Birth_year,Death_year,Affiliation,Rationale,Country_of_birth,Officialstatename,InternetccTLD,iso2,iso3
0,1901,"Jacobus Henricus van 't Hoff , Emil Fischer , ...",Jacobus Henricus van 't Hoff,1852,1911,Humboldt University of Berlin,"""[for his] discovery of the laws of chemical d...",NETHERLANDS (THE),The Kingdom of the Netherlands,.nl,NL,NLD
1,1902,"Emil Fischer , Svante Arrhenius , Henri Moissa...",Hermann Emil Fischer,1852,1919,Humboldt University of Berlin,"""[for] his work on sugar and purine syntheses""",GERMANY,The Federal Republic of Germany,.de,DE,DEU
2,1903,"Svante Arrhenius , Henri Moissan , Marcellin B...",Svante August Arrhenius,1859,1927,Stockholm University,"""[for] his electrolytic theory of dissociation""",SWEDEN,The Kingdom of Sweden,.se,SE,SWE
3,1904,"Henri Moissan , Marcellin Berthelot , William ...",Sir William Ramsay,1852,1916,University College London,"""[for his] discovery of the inert gaseous elem...",UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
4,1905,"Henri Moissan , Adolf von Baeyer , Theodore Wi...",Adolf von Baeyer,1835,1917,Ludwig Maximilian University of Munich,"""[for] the advancement of organic chemistry an...",GERMANY,The Federal Republic of Germany,.de,DE,DEU
...,...,...,...,...,...,...,...,...,...,...,...,...
197,2022,NaN,Morten Meldal,1954,Alive,University of Copenhagen,"""for the development of click chemistry and bi...",DENMARK,The Kingdom of Denmark,.dk,DK,DNK
198,2022,NaN,K. Barry Sharpless,1941,Alive,Scripps Research,"""for the development of click chemistry and bi...",UNITED STATES MINOR OUTLYING ISLANDS (THE),"Baker¬†Island, Howland¬†Island, Jarvis¬†Island...",NaN,UM,UMI
199,2023,NaN,Moungi G. Bawendi,1961,Alive,Massachusetts Institute of Technology,"""for the discovery and synthesis of quantum dots""",UNITED STATES MINOR OUTLYING ISLANDS (THE),"Baker¬†Island, Howland¬†Island, Jarvis¬†Island...",NaN,UM,UMI
200,2023,NaN,Louis E. Brus,1943,Alive,Columbia University,"""for the discovery and synthesis of quantum dots""",UNITED STATES MINOR OUTLYING ISLANDS (THE),"Baker¬†Island, Howland¬†Island, Jarvis¬†Island...",NaN,UM,UMI
201,2023,NaN,Alexey Ekimov,1945,Alive,NaN,"""for the discovery and synthesis of quantum dots""",RUSSIAN FEDERATION (THE),The Russian Federation,.ru,RU,RUS

In [1461]:
Nobel_Chemistry_countryisos_DF.columns

Index(['Year_of_award', 'Nominees', 'Laureate', 'Birth_year', 'Death_year',
       'Affiliation', 'Rationale', 'Country_of_birth', 'Officialstatename',
       'InternetccTLD', 'iso2', 'iso3'],
      dtype='object')

In [1462]:
#Transformación de la tabla a horizontal para clasificar a los ganadores por país de nacimiento
Nobel_Chemistry_countryisos_DF_wide=pd.pivot_table(Nobel_Chemistry_countryisos_DF,
               values=["Laureate"], # values to use
               index=['Country_of_birth'], # unit of analysis
               columns=['Year_of_award'], # the values for NEW column
                aggfunc=lambda x: ' '.join(str(v) for v in x))

Nobel_Chemistry_countryisos_DF_wide

                                                                        Laureate  \
Year_of_award                                                               1901
Country_of_birth
ARGENTINA                                                                    NaN
AUSTRALIA                                                                    NaN
AUSTRIA                                                                      NaN
BELGIUM                                                                      NaN
BOSNIA AND HERZEGOVINA                                                       NaN
CANADA                                                                       NaN
CROATIA                                                                      NaN
CZECHIA                                                                      NaN
DENMARK                                                                      NaN
FINLAND                                                                      NaN
FRANCE                                                                       NaN
GERMANY                                                                      NaN
HUNGARY                                                                      NaN
ISRAEL                                                                       NaN
ITALY                                                                        NaN
JAPAN                                                                        NaN
MEXICO                                                                       NaN
NETHERLANDS (THE)                                   Jacobus Henricus van 't Hoff
NORWAY                                                                       NaN
Not awarded                                                                  NaN
POLAND                                                                       NaN
RUSSIAN FEDERATION (THE)                                                     NaN
SWEDEN                                                                       NaN
SWITZERLAND                                                                  NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...                           NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                                   NaN

                                                                          \
Year_of_award                                                       1902
Country_of_birth
ARGENTINA                                                            NaN
AUSTRALIA                                                            NaN
AUSTRIA                                                              NaN
BELGIUM                                                              NaN
BOSNIA AND HERZEGOVINA                                               NaN
CANADA                                                               NaN
CROATIA                                                              NaN
CZECHIA                                                              NaN
DENMARK                                                              NaN
FINLAND                                                              NaN
FRANCE                                                               NaN
GERMANY                                             Hermann Emil Fischer
HUNGARY                                                              NaN
ISRAEL                                                               NaN
ITALY                                                                NaN
JAPAN                                                                NaN
MEXICO                                                               NaN
NETHERLANDS (THE)                                                    NaN
NORWAY                                                               NaN
Not awarded                                                          NaN
POLAND                                                               NaN
RUSSIAN FEDERATION (THE)                                             NaN
SWEDEN                                                               NaN
SWITZERLAND                                                          NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...                   NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                           NaN

                                                                             \
Year_of_award                                                          1903
Country_of_birth
ARGENTINA                                                               NaN
AUSTRALIA                                                               NaN
AUSTRIA                                                                 NaN
BELGIUM                                                                 NaN
BOSNIA AND HERZEGOVINA                                                  NaN
CANADA                                                                  NaN
CROATIA                                                                 NaN
CZECHIA                                                                 NaN
DENMARK                                                                 NaN
FINLAND                                                                 NaN
FRANCE                                                                  NaN
GERMANY                                                                 NaN
HUNGARY                                                                 NaN
ISRAEL                                                                  NaN
ITALY                                                                   NaN
JAPAN                                                                   NaN
MEXICO                                                                  NaN
NETHERLANDS (THE)                                                       NaN
NORWAY                                                                  NaN
Not awarded                                                             NaN
POLAND                                                                  NaN
RUSSIAN FEDERATION (THE)                                                NaN
SWEDEN                                              Svante August Arrhenius
SWITZERLAND                                                             NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...                      NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                              NaN

                                                                        \
Year_of_award                                                     1904
Country_of_birth
ARGENTINA                                                          NaN
AUSTRALIA                                                          NaN
AUSTRIA                                                            NaN
BELGIUM                                                            NaN
BOSNIA AND HERZEGOVINA                                             NaN
CANADA                                                             NaN
CROATIA                                                            NaN
CZECHIA                                                            NaN
DENMARK                                                            NaN
FINLAND                                                            NaN
FRANCE                                                             NaN
GERMANY                                                            NaN
HUNGARY                                                            NaN
ISRAEL                                                             NaN
ITALY                                                              NaN
JAPAN                                                              NaN
MEXICO                                                             NaN
NETHERLANDS (THE)                                                  NaN
NORWAY                                                             NaN
Not awarded                                                        NaN
POLAND                                                             NaN
RUSSIAN FEDERATION (THE)                                           NaN
SWEDEN                                                             NaN
SWITZERLAND                                                        NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...  Sir William Ramsay
UNITED STATES MINOR OUTLYING ISLANDS (THE)                         NaN

                                                                      \
Year_of_award                                                   1905
Country_of_birth
ARGENTINA                                                        NaN
AUSTRALIA                                                        NaN
AUSTRIA                                                          NaN
BELGIUM                                                          NaN
BOSNIA AND HERZEGOVINA                                           NaN
CANADA                                                           NaN
CROATIA                                                          NaN
CZECHIA                                                          NaN
DENMARK                                                          NaN
FINLAND                                                          NaN
FRANCE                                                           NaN
GERMANY                                             Adolf von Baeyer
HUNGARY                                                          NaN
ISRAEL                                                           NaN
ITALY                                                            NaN
JAPAN                                                            NaN
MEXICO                                                           NaN
NETHERLANDS (THE)                                                NaN
NORWAY                                                           NaN
Not awarded                                                      NaN
POLAND                                                           NaN
RUSSIAN FEDERATION (THE)                                         NaN
SWEDEN                                                           NaN
SWITZERLAND                                                      NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...               NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                       NaN

                                                                   \
Year_of_award                                                1906
Country_of_birth
ARGENTINA                                                     NaN
AUSTRALIA                                                     NaN
AUSTRIA                                                       NaN
BELGIUM                                                       NaN
BOSNIA AND HERZEGOVINA                                        NaN
CANADA                                                        NaN
CROATIA                                                       NaN
CZECHIA                                                       NaN
DENMARK                                                       NaN
FINLAND                                                       NaN
FRANCE                                              Henri Moissan
GERMANY                                                       NaN
HUNGARY                                                       NaN
ISRAEL                                                        NaN
ITALY                                                         NaN
JAPAN                                                         NaN
MEXICO                                                        NaN
NETHERLANDS (THE)                                             NaN
NORWAY                                                        NaN
Not awarded                                                   NaN
POLAND                                                        NaN
RUSSIAN FEDERATION (THE)                                      NaN
SWEDEN                                                        NaN
SWITZERLAND                                                   NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...            NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                    NaN

                                                                    \
Year_of_award                                                 1907
Country_of_birth
ARGENTINA                                                      NaN
AUSTRALIA                                                      NaN
AUSTRIA                                                        NaN
BELGIUM                                                        NaN
BOSNIA AND HERZEGOVINA                                         NaN
CANADA                                                         NaN
CROATIA                                                        NaN
CZECHIA                                                        NaN
DENMARK                                                        NaN
FINLAND                                                        NaN
FRANCE                                                         NaN
GERMANY                                             Eduard Buchner
HUNGARY                                                        NaN
ISRAEL                                                         NaN
ITALY                                                          NaN
JAPAN                                                          NaN
MEXICO                                                         NaN
NETHERLANDS (THE)                                              NaN
NORWAY                                                         NaN
Not awarded                                                    NaN
POLAND                                                         NaN
RUSSIAN FEDERATION (THE)                                       NaN
SWEDEN                                                         NaN
SWITZERLAND                                                    NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...             NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                     NaN

                                                                       \
Year_of_award                                                    1908
Country_of_birth
ARGENTINA                                                         NaN
AUSTRALIA                                                         NaN
AUSTRIA                                                           NaN
BELGIUM                                                           NaN
BOSNIA AND HERZEGOVINA                                            NaN
CANADA                                                            NaN
CROATIA                                                           NaN
CZECHIA                                                           NaN
DENMARK                                                           NaN
FINLAND                                                           NaN
FRANCE                                                            NaN
GERMANY                                                           NaN
HUNGARY                                                           NaN
ISRAEL                                                            NaN
ITALY                                                             NaN
JAPAN                                                             NaN
MEXICO                                                            NaN
NETHERLANDS (THE)                                                 NaN
NORWAY                                                            NaN
Not awarded                                                       NaN
POLAND                                                            NaN
RUSSIAN FEDERATION (THE)                                          NaN
SWEDEN                                                            NaN
SWITZERLAND                                                       NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...  Ernest Rutherford
UNITED STATES MINOR OUTLYING ISLANDS (THE)                        NaN

                                                                     \
Year_of_award                                                  1909
Country_of_birth
ARGENTINA                                                       NaN
AUSTRALIA                                                       NaN
AUSTRIA                                                         NaN
BELGIUM                                                         NaN
BOSNIA AND HERZEGOVINA                                          NaN
CANADA                                                          NaN
CROATIA                                                         NaN
CZECHIA                                                         NaN
DENMARK                                                         NaN
FINLAND                                                         NaN
FRANCE                                                          NaN
GERMANY                                             Wilhelm Ostwald
HUNGARY                                                         NaN
ISRAEL                                                          NaN
ITALY                                                           NaN
JAPAN                                                           NaN
MEXICO                                                          NaN
NETHERLANDS (THE)                                               NaN
NORWAY                                                          NaN
Not awarded                                                     NaN
POLAND                                                          NaN
RUSSIAN FEDERATION (THE)                                        NaN
SWEDEN                                                          NaN
SWITZERLAND                                                     NaN
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IR...              NaN
UNITED STATES MINOR OUTLYING ISLANDS (THE)                      NaN

                                                                  ...  \
Year_of_award                                               1910  ...
Country_of_birth                                                  ...
ARGENTINA                                                    NaN  ...
AUSTRALIA                                                    NaN  ...
AUSTRIA                                                      NaN  ...
BELGIUM                                                      NaN  ...
BOSNIA AND HERZEGOVINA                                       NaN  ...
CANADA                                                       NaN  ...
CROATIA                                                      NaN  ...
CZECHIA                                                      NaN  ...
DENMARK                                                      NaN  ...
FINLAND                                                      NaN  ...
FRANCE                                                       NaN  ...
GERMANY                                             Otto Wallach  ...
HUNGARY                                                      NaN  ...
ISRAEL                                                       NaN  ...
ITALY                                                        NaN  ...
JAPAN                                                        NaN  ...
MEXICO                                                       NaN  ...
NETHERLANDS (THE)                                            NaN  ...
NORWAY                                                       NaN  ...
Not awarded                                                  NaN  ...
POLAND                                                       NaN  ...
RUSSIAN FEDERATION (THE)                                     NaN  ...
SWEDEN                                                       NaN  ...